apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-15
  template:
    metadata:
      labels:
        app: env-15
    spec:
      containers:
      - name: env-15
        image: ghcr.io/maskaravivek/ephemeral-pr-env-vcluster:dfd926e9
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080