apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ephemeral-pr-env-vcluster-preview
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: maskaravivek
          repo: ephemeral-pr-env-vcluster # (1)
          tokenRef:
            key: token
            secretName: github-token
        requeueAfterSeconds: 30
  template:
    metadata:
      # This is the name of the Argo CD "Application" created for each PR
      name: 'env-{{ branch }}-{{ number }}'
    spec:
      project: default
      destination:
        namespace: crossplane-system
        server: 'https://kubernetes.default.svc'
      source:
        repoURL: 'https://github.com/maskaravivek/ephemeral-pr-env-vcluster'
        targetRevision: HEAD
        # We assume there's a minimal Helm chart under "crossplane/" that defines the Environment.
        # If using Kustomize or plain YAML, adjust accordingly.
        path: preview-crossplane/
        helm:
          # Optional: If you have a values.yaml or need to pass parameters
          valueFiles:
            - values.yaml
          parameters:
            - name: environmentName
              value: 'env-{{ number }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true