name: create-pr-preview

# on merge to main from pull request (recommended)
on:
  pull_request:
    # types: [opened, reopened, synchronize]
    # # types: [labeled]
    # branches:
    #   - main
env:
  REPO_NAME: ${{ github.event.repository.name }}
  PR_LINK: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}

jobs:
  create-preview-env:
    # if: ${{ github.event.label.name == 'preview' }}
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      pull-requests: write
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Get the GKE credentials so we can deploy to the cluster
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: "us-west2"

      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main

      - name: Login to vCluster Platform instance
        env:
          LOFT_URL: ${{ secrets.LOFT_URL }}
          ACCESS_KEY: ${{ secrets.LOFT_ACCESS_KEY }}
        run: vcluster platform login $LOFT_URL --access-key $ACCESS_KEY

      - id: create-preview-vcluster
        run: |
          vcluster create $REPO_NAME-pr-${{ github.event.pull_request.number }} 
            --template preview-template \
            --link "GitHub PR=$PR_LINK" \
            --link "Preview=https://${{ env.REPO_NAME}}-pr-${{ github.event.pull_request.number }}-vcluster-pro.us.demo.dev" \
            --link "Argo CD=https://34.94.198.226/applications/argocd/${{ env.REPO_NAME}}-${{ github.event.pull_request.head.ref }}-pr${{ github.event.pull_request.number }}?view=tree"

      - id: trigger-argocd-appset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "preview-cluster-ready"

      - id: add-pr-link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          header: release
          message: |
            [Preview environment app link](https://${{ env.REPO_NAME}}-pr-${{ github.event.pull_request.number }}-vcluster-pro.us.demo.dev)
            
            [Argo CD App](https://argocd-vcluster-pro.us.demo.dev/applications/argocd/${{ env.REPO_NAME}}-${{ github.event.pull_request.head.ref }}-pr${{ github.event.pull_request.number }}?view=tree)
            
            [Preview vcluster pods](https://vcluster-pro.us.demo.dev/projects/api-framework/vclusters/$REPO_NAME-pr-${{ github.event.pull_request.number }}/pods)
            