name: create-vcluster

on:
  workflow_dispatch:
  
env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  create-vcluster:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main

      - name: Login to vCluster Platform instance
        env:
          LOFT_URL: ${{ secrets.LOFT_URL }}
          ACCESS_KEY: ${{ secrets.LOFT_ACCESS_KEY }}
        run: vcluster login $LOFT_URL --access-key $ACCESS_KEY

      - id: create-vcluster
        run: |
          vcluster create $REPO_NAME
          vcluster use $REPO_NAME