name: create-pr-preview

# on merge to main from pull request (recommended)
on:
  workflow_dispatch:
    
  # pull_request:
    # types: [opened, reopened, synchronize]
    # # types: [labeled]
    # branches:
    #   - main
env:
  REPO_NAME: ${{ github.event.repository.name }}
  PR_LINK: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}

permissions:
  contents: write  # <-- This grants permission for the workflow to push changes

jobs:
  create-preview-env:
    # if: ${{ github.event.label.name == 'preview' }}
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      # - name: Configure git
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "actions@github.com"
      # Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Get the GKE credentials so we can deploy to the cluster
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: "us-west2"

      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main

      - name: Login to vCluster Platform instance
        env:
          LOFT_URL: ${{ secrets.LOFT_URL }}
          ACCESS_KEY: ${{ secrets.LOFT_ACCESS_KEY }}
        run: vcluster platform login $LOFT_URL --access-key $ACCESS_KEY

      - id: create-preview-vcluster
        run: |
          vcluster create $REPO_NAME-pr-${{ github.event.pull_request.number }} \
            --template preview-template \
            --link "GitHub PR=$PR_LINK" \
            --link "Preview=https://${{ env.REPO_NAME}}-pr-${{ github.event.pull_request.number }}-vcluster-pro.us.demo.dev" \
            --link "Argo CD=https://34.94.198.226/applications/argocd/${{ env.REPO_NAME}}-${{ github.event.pull_request.head.ref }}-pr${{ github.event.pull_request.number }}?view=tree"

      - name: Create Ephemeral Env Resource
        env:
          REPO_TOKEN: ${{ secrets.GHA_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.number }}"
          cat <<EOF > gitops/ephemeral/ephemeralvcluster-pr${PR_NUMBER}.yaml
          apiVersion: example.org/v1alpha1
          kind: EphemeralVCluster
          metadata:
            name: pr${PR_NUMBER}
          spec:
            prNumber: "${PR_NUMBER}"
            # add more fields as needed
          EOF
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Create ephemeralvcluster resource for PR #${{ github.event.number }}"
          commit_options: '--no-verify'
          repository: .
          file_pattern: gitops/ephemeral/ephemeralvcluster-pr${{ github.event.number }}.yaml
          branch: ${{ github.head_ref }}

      - name: Post comment with vCluster URL
        # This step queries the newly created vCluster LoadBalancer or Ingress, then posts a link in the PR.
        run: |
          # Example retrieving LB IP or Ingress:
          VCLUSTER_IP=$(kubectl get svc -n crossplane-system vcluster-pr${PR_NUMBER}-vcluster \
                       -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          COMMENT_BODY="Ephemeral environment is up! Access it at http://${VCLUSTER_IP}"
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -X POST \
               -d "{\"body\":\"$COMMENT_BODY\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

      # - id: trigger-argocd-appset
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: |
      #     gh pr edit ${{ github.event.pull_request.number }} --add-label "preview-cluster-ready"

      # - id: add-pr-link
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     number: ${{ github.event.pull_request.number }}
      #     header: release
      #     message: |
      #       [Preview environment app link](https://${{ env.REPO_NAME}}-pr-${{ github.event.pull_request.number }}-vcluster-pro.us.demo.dev)
            
      #       [Argo CD App](https://argocd-vcluster-pro.us.demo.dev/applications/argocd/${{ env.REPO_NAME}}-${{ github.event.pull_request.head.ref }}-pr${{ github.event.pull_request.number }}?view=tree)
            
      #       [Preview vcluster pods](https://vcluster-pro.us.demo.dev/projects/api-framework/vclusters/$REPO_NAME-pr-${{ github.event.pull_request.number }}/pods)
            